server:
  port: 8083

spring:
  application:
    name: enterprise-system

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
