server:
  port: 8085

spring:
  application:
    name: enterprise-business

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
